name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
jobs:
  build:
    runs-on: python-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: "alkarakully"
          password: "sodsod84@D"

      # Step 3: Set up Docker Buildx (optional but recommended for cross-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t alkarakully/tssdata-draw:v3.0 .

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push alkarakully/tssdata-draw:v3.0
